runtime: nodejs18  # or nodejs16, depending on your Node version
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"

buildenv: flex
beta_settings:
  cloud_sql_instances: your-instance-connection-name

manual_scaling:
  instances: 1

buildpack: gcr.io/buildpacks/nodejs
